sudo: false
language: ruby
rvm:
  - 2.5.3
services:
  - postgresql
  - redis-server
addons:
  postgresql: '9.4'
before_install: gem install bundler -v 1.16.1
before_script:
  - RAILS_ENV=test bundle exec rails db:create
